---
version: 2
jobs:
  build:
    working_directory: ~/apidocs
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout

      # Restore Cached Dependencies
      - type: cache-restore
        name: Restore bundle cache
        key: apidocs-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run: bundle install --path vendor/bundle

      # Cache Dependencies
      - type: cache-save
        name: Store bundle cache
        key: apidocs-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      - run: git config --global user.email "devops@zinc.io"
      - run: git config --global user.name "ApiDocs Deploy"


      # Setup the database
      - run: ALLOW_DIRTY=true bundle exec rake publish